INSERT INTO "TemplateProduct" ("id", "templateId", "category", "name", "isSaleable", "participateAllocation", "allocationWeight", "sortOrder", "remark") VALUES
('tp_highrise住宅', 'tpl_residential_standard', '住宅类', '高层住宅', true, true, 1, 1, '默认可售业态'),
('tp_midrise住宅', 'tpl_residential_standard', '住宅类', '小高层住宅', true, true, 1, 2, '默认可售业态'),
('tp_garden住宅', 'tpl_residential_standard', '住宅类', '洋房住宅', true, true, 1, 3, '默认可售业态'),
('tp_townhouse住宅', 'tpl_residential_standard', '住宅类', '叠拼/联排', true, true, 1, 4, '按项目需要选择'),
('tp_villa住宅', 'tpl_residential_standard', '住宅类', '别墅/合院', true, true, 1, 5, '按项目需要选择'),
('tp_chinese_courtyard住宅', 'tpl_residential_standard', '住宅类', '中式合院', true, true, 1, 6, '按项目需要选择'),
('tp_shop商业', 'tpl_residential_standard', '商业商办', '底商', true, true, 1, 101, '默认可售业态'),
('tp_independent_commercial商业', 'tpl_residential_standard', '商业商办', '独立商业', true, true, 1, 102, '按项目需要选择'),
('tp_commercial_street商业', 'tpl_residential_standard', '商业商办', '商业街', true, true, 1, 103, '按项目需要选择'),
('tp_complex商业', 'tpl_residential_standard', '商业商办', '商业综合体', true, true, 1, 104, '按项目需要选择'),
('tp_office商业', 'tpl_residential_standard', '商业商办', '办公', true, true, 1, 105, '按项目需要选择'),
('tp_loft商业', 'tpl_residential_standard', '商业商办', '公寓/LOFT', true, true, 1, 106, '按项目需要选择'),
('tp_hotel商业', 'tpl_residential_standard', '商业商办', '酒店', true, true, 1, 107, '按项目需要选择'),
('tp_club商业', 'tpl_residential_standard', '商业商办', '会所', false, false, 0, 108, '通常不可售，可按项目调整'),
('tp_parking_property车位', 'tpl_residential_standard', '车位储藏', '地下产权车位', true, true, 1, 201, '车位收入进入收入明细表'),
('tp_parking_use车位', 'tpl_residential_standard', '车位储藏', '地下使用权车位', true, true, 1, 202, '车位收入进入收入明细表'),
('tp_parking_ground车位', 'tpl_residential_standard', '车位储藏', '地上车位', true, true, 1, 203, '按项目需要选择'),
('tp_parking_civil车位', 'tpl_residential_standard', '车位储藏', '人防车位', true, true, 1, 204, '按当地销售/使用权口径调整'),
('tp_storage车位', 'tpl_residential_standard', '车位储藏', '储藏室', true, true, 1, 205, '按项目需要选择'),
('tp_other_saleable车位', 'tpl_residential_standard', '车位储藏', '其他可售', true, true, 1, 206, '兜底可售项'),
('tp_prop配套', 'tpl_residential_standard', '配套用房', '物业用房', false, false, 0, 301, '不可售配套'),
('tp_community配套', 'tpl_residential_standard', '配套用房', '社区用房', false, false, 0, 302, '不可售配套'),
('tp_elderly配套', 'tpl_residential_standard', '配套用房', '养老用房', false, false, 0, 303, '按规划要求选择'),
('tp_childcare配套', 'tpl_residential_standard', '配套用房', '托育用房', false, false, 0, 304, '按规划要求选择'),
('tp_culture配套', 'tpl_residential_standard', '配套用房', '文化活动用房', false, false, 0, 305, '按规划要求选择'),
('tp_kindergarten配套', 'tpl_residential_standard', '配套用房', '幼儿园', false, false, 0, 306, '按规划要求选择'),
('tp_toilet配套', 'tpl_residential_standard', '配套用房', '公厕', false, false, 0, 307, '按规划要求选择'),
('tp_gatehouse配套', 'tpl_residential_standard', '配套用房', '门卫', false, false, 0, 308, '按规划要求选择'),
('tp_equipment_room配套', 'tpl_residential_standard', '配套用房', '设备用房', false, false, 0, 309, '按规划要求选择'),
('tp_highrise_basement地下', 'tpl_residential_standard', '地下空间', '高层主楼地下室', false, true, 1, 401, '主楼地下空间'),
('tp_garden_basement地下', 'tpl_residential_standard', '地下空间', '洋房主楼地下室', false, true, 1, 402, '主楼地下空间'),
('tp_villa_basement地下', 'tpl_residential_standard', '地下空间', '别墅地下室', false, true, 1, 403, '主楼地下空间'),
('tp_commercial_basement地下', 'tpl_residential_standard', '地下空间', '商业地下室', false, true, 1, 404, '商业地下空间'),
('tp_pure_basement地下', 'tpl_residential_standard', '地下空间', '非主楼纯地库', false, true, 1, 405, '参与成本分摊'),
('tp_civil_defense地下', 'tpl_residential_standard', '地下空间', '人防地下室', false, true, 1, 406, '人防地下空间'),
('tp_demo_area专项', 'tpl_residential_standard', '专项区域', '示范区', false, false, 0, 501, '销售展示相关区域'),
('tp_sales_office专项', 'tpl_residential_standard', '专项区域', '售楼部', false, false, 0, 502, '售楼部面积进入概况工程量'),
('tp_showflat专项', 'tpl_residential_standard', '专项区域', '样板间', false, false, 0, 503, '样板间面积进入概况工程量'),
('tp_private_garden专项', 'tpl_residential_standard', '专项区域', '私家庭院', false, false, 0, 504, '专项景观区域'),
('tp_sunken_garden专项', 'tpl_residential_standard', '专项区域', '下沉庭院', false, false, 0, 505, '专项景观区域'),
('tp_water_system专项', 'tpl_residential_standard', '专项区域', '水系', false, false, 0, 506, '专项景观区域'),
('tp_pool专项', 'tpl_residential_standard', '专项区域', '游泳池', false, false, 0, 507, '专项景观/设备区域')
ON CONFLICT ("templateId", "name") DO UPDATE SET
  "category" = EXCLUDED."category",
  "isSaleable" = EXCLUDED."isSaleable",
  "participateAllocation" = EXCLUDED."participateAllocation",
  "allocationWeight" = EXCLUDED."allocationWeight",
  "sortOrder" = EXCLUDED."sortOrder",
  "remark" = EXCLUDED."remark";
