import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const statements = [
  `CREATE TABLE IF NOT EXISTS "PriceIndicatorLibrary" (
    "id" TEXT PRIMARY KEY,
    "costCode" TEXT NOT NULL,
    "subjectName" TEXT,
    "indicatorName" TEXT NOT NULL,
    "region" TEXT DEFAULT '全国',
    "city" TEXT DEFAULT '通用',
    "productType" TEXT DEFAULT '通用',
    "stage" TEXT DEFAULT 'SCHEME',
    "standardLevel" TEXT DEFAULT '标准',
    "quantityUnit" TEXT,
    "pricingUnit" TEXT,
    "taxInclusiveUnitPrice" DECIMAL(18,4) DEFAULT 0,
    "taxExclusiveUnitPrice" DECIMAL(18,4) DEFAULT 0,
    "taxRate" DECIMAL(8,4) DEFAULT 0.09,
    "sourceType" TEXT DEFAULT 'experience',
    "sourceName" TEXT,
    "effectiveDate" TEXT,
    "confidence" DECIMAL(8,4) DEFAULT 0.6,
    "enabled" BOOLEAN DEFAULT TRUE,
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("costCode", "indicatorName", "region", "city", "productType", "stage", "standardLevel")
  )`,

  `CREATE TABLE IF NOT EXISTS "RecalculationLog" (
    "id" TEXT PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "projectVersionId" TEXT NOT NULL,
    "actionType" TEXT DEFAULT 'target_cost_recalculate',
    "stage" TEXT,
    "totalRows" INTEGER DEFAULT 0,
    "updatedRows" INTEGER DEFAULT 0,
    "ruleRows" INTEGER DEFAULT 0,
    "priceRows" INTEGER DEFAULT 0,
    "amountRows" INTEGER DEFAULT 0,
    "operatorName" TEXT,
    "status" TEXT DEFAULT 'success',
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE,
    FOREIGN KEY ("projectVersionId") REFERENCES "ProjectVersion"("id") ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "RecalculationLogLine" (
    "id" TEXT PRIMARY KEY,
    "logId" TEXT NOT NULL,
    "costLineId" TEXT,
    "costCode" TEXT,
    "costName" TEXT,
    "changeType" TEXT,
    "oldQuantity" DECIMAL(18,4) DEFAULT 0,
    "newQuantity" DECIMAL(18,4) DEFAULT 0,
    "oldUnitPrice" DECIMAL(18,4) DEFAULT 0,
    "newUnitPrice" DECIMAL(18,4) DEFAULT 0,
    "oldAmount" DECIMAL(18,4) DEFAULT 0,
    "newAmount" DECIMAL(18,4) DEFAULT 0,
    "source" TEXT,
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("logId") REFERENCES "RecalculationLog"("id") ON DELETE CASCADE,
    FOREIGN KEY ("costLineId") REFERENCES "CostLine"("id") ON DELETE SET NULL
  )`,

  `CREATE TABLE IF NOT EXISTS "ProcurementPackage" (
    "id" TEXT PRIMARY KEY,
    "projectVersionId" TEXT NOT NULL,
    "packageCode" TEXT,
    "packageName" TEXT NOT NULL,
    "packageType" TEXT DEFAULT '工程',
    "costCode" TEXT,
    "costSubjectId" TEXT,
    "scope" TEXT,
    "planStartDate" TEXT,
    "planEndDate" TEXT,
    "controlPrice" DECIMAL(18,4) DEFAULT 0,
    "targetAmount" DECIMAL(18,4) DEFAULT 0,
    "winningAmount" DECIMAL(18,4) DEFAULT 0,
    "taxRate" DECIMAL(8,4) DEFAULT 0.09,
    "status" TEXT DEFAULT 'planned',
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("projectVersionId") REFERENCES "ProjectVersion"("id") ON DELETE CASCADE,
    FOREIGN KEY ("costSubjectId") REFERENCES "CostSubject"("id") ON DELETE SET NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "ProcurementBid" (
    "id" TEXT PRIMARY KEY,
    "packageId" TEXT NOT NULL,
    "bidderName" TEXT NOT NULL,
    "contactName" TEXT,
    "bidAmount" DECIMAL(18,4) DEFAULT 0,
    "taxRate" DECIMAL(8,4) DEFAULT 0.09,
    "evaluatedAmount" DECIMAL(18,4) DEFAULT 0,
    "score" DECIMAL(8,4) DEFAULT 0,
    "ranking" INTEGER DEFAULT 0,
    "isWinner" BOOLEAN DEFAULT FALSE,
    "status" TEXT DEFAULT 'valid',
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("packageId") REFERENCES "ProcurementPackage"("id") ON DELETE CASCADE
  )`,

  `CREATE TABLE IF NOT EXISTS "Contract" (
    "id" TEXT PRIMARY KEY,
    "projectVersionId" TEXT NOT NULL,
    "packageId" TEXT,
    "contractCode" TEXT,
    "contractName" TEXT NOT NULL,
    "contractType" TEXT DEFAULT '工程合同',
    "contractorName" TEXT,
    "costCode" TEXT,
    "costSubjectId" TEXT,
    "taxInclusiveAmount" DECIMAL(18,4) DEFAULT 0,
    "taxExclusiveAmount" DECIMAL(18,4) DEFAULT 0,
    "taxAmount" DECIMAL(18,4) DEFAULT 0,
    "taxRate" DECIMAL(8,4) DEFAULT 0.09,
    "signedDate" TEXT,
    "startDate" TEXT,
    "endDate" TEXT,
    "status" TEXT DEFAULT 'draft',
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("projectVersionId") REFERENCES "ProjectVersion"("id") ON DELETE CASCADE,
    FOREIGN KEY ("packageId") REFERENCES "ProcurementPackage"("id") ON DELETE SET NULL,
    FOREIGN KEY ("costSubjectId") REFERENCES "CostSubject"("id") ON DELETE SET NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "ContractChange" (
    "id" TEXT PRIMARY KEY,
    "contractId" TEXT NOT NULL,
    "changeCode" TEXT,
    "changeName" TEXT NOT NULL,
    "changeType" TEXT DEFAULT '变更',
    "reason" TEXT,
    "taxInclusiveAmount" DECIMAL(18,4) DEFAULT 0,
    "taxExclusiveAmount" DECIMAL(18,4) DEFAULT 0,
    "taxAmount" DECIMAL(18,4) DEFAULT 0,
    "taxRate" DECIMAL(8,4) DEFAULT 0.09,
    "submitDate" TEXT,
    "approvedDate" TEXT,
    "status" TEXT DEFAULT 'draft',
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("contractId") REFERENCES "Contract"("id") ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "ContractPayment" (
    "id" TEXT PRIMARY KEY,
    "contractId" TEXT NOT NULL,
    "paymentCode" TEXT,
    "periodName" TEXT,
    "payableAmount" DECIMAL(18,4) DEFAULT 0,
    "paidAmount" DECIMAL(18,4) DEFAULT 0,
    "paymentRate" DECIMAL(8,4) DEFAULT 0,
    "plannedDate" TEXT,
    "paidDate" TEXT,
    "status" TEXT DEFAULT 'planned',
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("contractId") REFERENCES "Contract"("id") ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "ContractSettlement" (
    "id" TEXT PRIMARY KEY,
    "contractId" TEXT NOT NULL,
    "settlementCode" TEXT,
    "reportedAmount" DECIMAL(18,4) DEFAULT 0,
    "auditedAmount" DECIMAL(18,4) DEFAULT 0,
    "deductedAmount" DECIMAL(18,4) DEFAULT 0,
    "taxRate" DECIMAL(8,4) DEFAULT 0.09,
    "reportedDate" TEXT,
    "auditedDate" TEXT,
    "status" TEXT DEFAULT 'draft',
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("contractId") REFERENCES "Contract"("id") ON DELETE CASCADE
  )`,

  `CREATE TABLE IF NOT EXISTS "DynamicCostSnapshot" (
    "id" TEXT PRIMARY KEY,
    "projectVersionId" TEXT NOT NULL,
    "snapshotName" TEXT NOT NULL,
    "snapshotDate" TEXT,
    "targetCost" DECIMAL(18,4) DEFAULT 0,
    "contractAmount" DECIMAL(18,4) DEFAULT 0,
    "changeAmount" DECIMAL(18,4) DEFAULT 0,
    "settlementAmount" DECIMAL(18,4) DEFAULT 0,
    "pendingAmount" DECIMAL(18,4) DEFAULT 0,
    "dynamicCost" DECIMAL(18,4) DEFAULT 0,
    "riskAmount" DECIMAL(18,4) DEFAULT 0,
    "status" TEXT DEFAULT 'draft',
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("projectVersionId") REFERENCES "ProjectVersion"("id") ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "DynamicCostLine" (
    "id" TEXT PRIMARY KEY,
    "snapshotId" TEXT NOT NULL,
    "costSubjectId" TEXT,
    "costLineId" TEXT,
    "costCode" TEXT,
    "costName" TEXT,
    "targetAmount" DECIMAL(18,4) DEFAULT 0,
    "contractAmount" DECIMAL(18,4) DEFAULT 0,
    "changeAmount" DECIMAL(18,4) DEFAULT 0,
    "settlementAmount" DECIMAL(18,4) DEFAULT 0,
    "pendingAmount" DECIMAL(18,4) DEFAULT 0,
    "dynamicAmount" DECIMAL(18,4) DEFAULT 0,
    "deviationAmount" DECIMAL(18,4) DEFAULT 0,
    "deviationRate" DECIMAL(8,4) DEFAULT 0,
    "riskLevel" TEXT,
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("snapshotId") REFERENCES "DynamicCostSnapshot"("id") ON DELETE CASCADE,
    FOREIGN KEY ("costSubjectId") REFERENCES "CostSubject"("id") ON DELETE SET NULL,
    FOREIGN KEY ("costLineId") REFERENCES "CostLine"("id") ON DELETE SET NULL
  )`,

  `CREATE TABLE IF NOT EXISTS "FinancialEvaluationScenario" (
    "id" TEXT PRIMARY KEY,
    "projectVersionId" TEXT NOT NULL,
    "scenarioName" TEXT NOT NULL,
    "scenarioType" TEXT DEFAULT 'base',
    "priceChangeRate" DECIMAL(8,4) DEFAULT 0,
    "costChangeRate" DECIMAL(8,4) DEFAULT 0,
    "salesSpeedChangeRate" DECIMAL(8,4) DEFAULT 0,
    "fundingCostRate" DECIMAL(8,4) DEFAULT 0,
    "isDefault" BOOLEAN DEFAULT FALSE,
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("projectVersionId") REFERENCES "ProjectVersion"("id") ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "FinancialEvaluation" (
    "id" TEXT PRIMARY KEY,
    "projectVersionId" TEXT NOT NULL,
    "scenarioId" TEXT,
    "evaluationName" TEXT NOT NULL,
    "totalInvestment" DECIMAL(18,4) DEFAULT 0,
    "totalCost" DECIMAL(18,4) DEFAULT 0,
    "salesRevenue" DECIMAL(18,4) DEFAULT 0,
    "otherIncome" DECIMAL(18,4) DEFAULT 0,
    "grossProfit" DECIMAL(18,4) DEFAULT 0,
    "netProfit" DECIMAL(18,4) DEFAULT 0,
    "netMargin" DECIMAL(8,4) DEFAULT 0,
    "peakFunding" DECIMAL(18,4) DEFAULT 0,
    "irr" DECIMAL(8,4) DEFAULT 0,
    "npv" DECIMAL(18,4) DEFAULT 0,
    "paybackPeriod" DECIMAL(8,4) DEFAULT 0,
    "roi" DECIMAL(8,4) DEFAULT 0,
    "roe" DECIMAL(8,4) DEFAULT 0,
    "status" TEXT DEFAULT 'draft',
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("projectVersionId") REFERENCES "ProjectVersion"("id") ON DELETE CASCADE,
    FOREIGN KEY ("scenarioId") REFERENCES "FinancialEvaluationScenario"("id") ON DELETE SET NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "FinancialMetricLine" (
    "id" TEXT PRIMARY KEY,
    "evaluationId" TEXT NOT NULL,
    "metricCode" TEXT,
    "metricName" TEXT NOT NULL,
    "metricGroup" TEXT,
    "metricValue" DECIMAL(18,4) DEFAULT 0,
    "unit" TEXT,
    "benchmarkValue" DECIMAL(18,4) DEFAULT 0,
    "deviation" DECIMAL(18,4) DEFAULT 0,
    "remark" TEXT,
    "sortOrder" INTEGER DEFAULT 0,
    FOREIGN KEY ("evaluationId") REFERENCES "FinancialEvaluation"("id") ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CashFlowLine" (
    "id" TEXT PRIMARY KEY,
    "evaluationId" TEXT NOT NULL,
    "periodIndex" INTEGER DEFAULT 0,
    "periodName" TEXT,
    "cashInflow" DECIMAL(18,4) DEFAULT 0,
    "salesCollection" DECIMAL(18,4) DEFAULT 0,
    "otherInflow" DECIMAL(18,4) DEFAULT 0,
    "cashOutflow" DECIMAL(18,4) DEFAULT 0,
    "landPayment" DECIMAL(18,4) DEFAULT 0,
    "constructionPayment" DECIMAL(18,4) DEFAULT 0,
    "taxPayment" DECIMAL(18,4) DEFAULT 0,
    "financePayment" DECIMAL(18,4) DEFAULT 0,
    "netCashFlow" DECIMAL(18,4) DEFAULT 0,
    "cumulativeCashFlow" DECIMAL(18,4) DEFAULT 0,
    "remark" TEXT,
    FOREIGN KEY ("evaluationId") REFERENCES "FinancialEvaluation"("id") ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "SensitivityAnalysisLine" (
    "id" TEXT PRIMARY KEY,
    "evaluationId" TEXT NOT NULL,
    "factorType" TEXT NOT NULL,
    "changeRate" DECIMAL(8,4) DEFAULT 0,
    "salesRevenue" DECIMAL(18,4) DEFAULT 0,
    "totalCost" DECIMAL(18,4) DEFAULT 0,
    "netProfit" DECIMAL(18,4) DEFAULT 0,
    "netMargin" DECIMAL(8,4) DEFAULT 0,
    "irr" DECIMAL(8,4) DEFAULT 0,
    "paybackPeriod" DECIMAL(8,4) DEFAULT 0,
    "remark" TEXT,
    FOREIGN KEY ("evaluationId") REFERENCES "FinancialEvaluation"("id") ON DELETE CASCADE
  )`,

  `CREATE TABLE IF NOT EXISTS "AIKnowledgeDocument" (
    "id" TEXT PRIMARY KEY,
    "projectId" TEXT,
    "projectVersionId" TEXT,
    "title" TEXT NOT NULL,
    "docType" TEXT DEFAULT 'cost_knowledge',
    "sourceType" TEXT DEFAULT 'manual',
    "sourceName" TEXT,
    "region" TEXT,
    "productType" TEXT,
    "stage" TEXT,
    "content" TEXT,
    "tags" TEXT,
    "enabled" BOOLEAN DEFAULT TRUE,
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL,
    FOREIGN KEY ("projectVersionId") REFERENCES "ProjectVersion"("id") ON DELETE SET NULL
  )`,
  `CREATE TABLE IF NOT EXISTS "AIKnowledgeChunk" (
    "id" TEXT PRIMARY KEY,
    "documentId" TEXT NOT NULL,
    "chunkIndex" INTEGER DEFAULT 0,
    "chunkText" TEXT NOT NULL,
    "summary" TEXT,
    "keywords" TEXT,
    "embeddingRef" TEXT,
    "confidence" DECIMAL(8,4) DEFAULT 0.6,
    "enabled" BOOLEAN DEFAULT TRUE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("documentId") REFERENCES "AIKnowledgeDocument"("id") ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "AICostBenchmark" (
    "id" TEXT PRIMARY KEY,
    "costCode" TEXT,
    "costName" TEXT,
    "region" TEXT DEFAULT '全国',
    "city" TEXT DEFAULT '通用',
    "productType" TEXT DEFAULT '通用',
    "stage" TEXT DEFAULT 'SCHEME',
    "standardLevel" TEXT DEFAULT '标准',
    "metricName" TEXT,
    "metricValue" DECIMAL(18,4) DEFAULT 0,
    "unit" TEXT,
    "minValue" DECIMAL(18,4) DEFAULT 0,
    "maxValue" DECIMAL(18,4) DEFAULT 0,
    "sourceDocumentId" TEXT,
    "confidence" DECIMAL(8,4) DEFAULT 0.6,
    "enabled" BOOLEAN DEFAULT TRUE,
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("sourceDocumentId") REFERENCES "AIKnowledgeDocument"("id") ON DELETE SET NULL
  )`,

  `CREATE TABLE IF NOT EXISTS "OperationLog" (
    "id" TEXT PRIMARY KEY,
    "projectId" TEXT,
    "projectVersionId" TEXT,
    "module" TEXT,
    "action" TEXT NOT NULL,
    "targetType" TEXT,
    "targetId" TEXT,
    "beforeData" TEXT,
    "afterData" TEXT,
    "operatorName" TEXT,
    "remark" TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL,
    FOREIGN KEY ("projectVersionId") REFERENCES "ProjectVersion"("id") ON DELETE SET NULL
  )`
];

const indexes = [
  `CREATE INDEX IF NOT EXISTS "PriceIndicatorLibrary_costCode_idx" ON "PriceIndicatorLibrary" ("costCode")`,
  `CREATE INDEX IF NOT EXISTS "PriceIndicatorLibrary_city_stage_idx" ON "PriceIndicatorLibrary" ("city", "stage")`,
  `CREATE INDEX IF NOT EXISTS "PriceIndicatorLibrary_enabled_idx" ON "PriceIndicatorLibrary" ("enabled")`,
  `CREATE INDEX IF NOT EXISTS "RecalculationLog_projectVersionId_idx" ON "RecalculationLog" ("projectVersionId")`,
  `CREATE INDEX IF NOT EXISTS "RecalculationLogLine_logId_idx" ON "RecalculationLogLine" ("logId")`,
  `CREATE INDEX IF NOT EXISTS "ProcurementPackage_projectVersionId_idx" ON "ProcurementPackage" ("projectVersionId")`,
  `CREATE INDEX IF NOT EXISTS "ProcurementBid_packageId_idx" ON "ProcurementBid" ("packageId")`,
  `CREATE INDEX IF NOT EXISTS "Contract_projectVersionId_idx" ON "Contract" ("projectVersionId")`,
  `CREATE INDEX IF NOT EXISTS "Contract_packageId_idx" ON "Contract" ("packageId")`,
  `CREATE INDEX IF NOT EXISTS "ContractChange_contractId_idx" ON "ContractChange" ("contractId")`,
  `CREATE INDEX IF NOT EXISTS "ContractPayment_contractId_idx" ON "ContractPayment" ("contractId")`,
  `CREATE INDEX IF NOT EXISTS "ContractSettlement_contractId_idx" ON "ContractSettlement" ("contractId")`,
  `CREATE INDEX IF NOT EXISTS "DynamicCostSnapshot_projectVersionId_idx" ON "DynamicCostSnapshot" ("projectVersionId")`,
  `CREATE INDEX IF NOT EXISTS "DynamicCostLine_snapshotId_idx" ON "DynamicCostLine" ("snapshotId")`,
  `CREATE INDEX IF NOT EXISTS "FinancialEvaluationScenario_projectVersionId_idx" ON "FinancialEvaluationScenario" ("projectVersionId")`,
  `CREATE INDEX IF NOT EXISTS "FinancialEvaluation_projectVersionId_idx" ON "FinancialEvaluation" ("projectVersionId")`,
  `CREATE INDEX IF NOT EXISTS "FinancialMetricLine_evaluationId_idx" ON "FinancialMetricLine" ("evaluationId")`,
  `CREATE INDEX IF NOT EXISTS "CashFlowLine_evaluationId_idx" ON "CashFlowLine" ("evaluationId")`,
  `CREATE INDEX IF NOT EXISTS "SensitivityAnalysisLine_evaluationId_idx" ON "SensitivityAnalysisLine" ("evaluationId")`,
  `CREATE INDEX IF NOT EXISTS "AIKnowledgeDocument_projectId_idx" ON "AIKnowledgeDocument" ("projectId")`,
  `CREATE INDEX IF NOT EXISTS "AIKnowledgeDocument_docType_idx" ON "AIKnowledgeDocument" ("docType")`,
  `CREATE INDEX IF NOT EXISTS "AIKnowledgeChunk_documentId_idx" ON "AIKnowledgeChunk" ("documentId")`,
  `CREATE INDEX IF NOT EXISTS "AICostBenchmark_costCode_idx" ON "AICostBenchmark" ("costCode")`,
  `CREATE INDEX IF NOT EXISTS "AICostBenchmark_city_stage_idx" ON "AICostBenchmark" ("city", "stage")`,
  `CREATE INDEX IF NOT EXISTS "OperationLog_projectVersionId_idx" ON "OperationLog" ("projectVersionId")`,
  `CREATE INDEX IF NOT EXISTS "OperationLog_action_idx" ON "OperationLog" ("action")`
];

async function main() {
  for (const sql of statements) await prisma.$executeRawUnsafe(sql);
  for (const sql of indexes) await prisma.$executeRawUnsafe(sql);
  console.log(`Ensured database foundation tables: ${statements.length}, indexes: ${indexes.length}.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
