import Link from 'next/link';
import { prisma } from '@/lib/prisma';

export const dynamic = 'force-dynamic';

export default async function TemplatesPage() {
  const templates = await prisma.template.findMany({
    orderBy: { sortOrder: 'asc' },
    include: { products: { orderBy: { sortOrder: 'asc' } }, costRules: { orderBy: { sortOrder: 'asc' } }, taxRules: { orderBy: { sortOrder: 'asc' } } }
  });
  return <main className="page"><div className="container"><div className="page-header"><div><p className="eyebrow">后台模板中心</p><h1 className="title">默认模板库</h1><p className="subtitle">这里维护标准业态、科目规则、税率和分摊口径。新建项目时复制模板快照，项目内数据不反向影响后台模板。</p></div><div className="actions" style={{ marginTop: 0 }}><Link href="/projects" className="btn">项目列表</Link><Link href="/projects/new" className="btn btn-primary">用模板新建项目</Link></div></div>{templates.length === 0 ? <section className="card"><h2>暂无模板</h2><p className="meta">部署迁移完成后会自动生成“住宅开发目标成本标准模板”。</p></section> : <div style={{ display: 'grid', gap: 16 }}>{templates.map((tpl) => <section key={tpl.id} className="card"><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12 }}><div><span className="badge">{tpl.isDefault ? '默认模板' : tpl.type}</span><h2 style={{ marginTop: 10 }}>{tpl.name}</h2><p className="meta">{tpl.description || '暂无说明'}</p></div><div className="stat"><div className="stat-label">业态/规则/税率</div><div className="stat-value">{tpl.products.length}/{tpl.costRules.length}/{tpl.taxRules.length}</div></div></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 12, marginTop: 12 }}><div style={{ border: '1px solid #eef2f6', borderRadius: 10, padding: 12 }}><b>业态模板</b><p className="meta">项目创建时选择需要的业态，不需要的不占项目篇幅。</p>{tpl.products.slice(0, 12).map((p) => <div key={p.id} style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0', borderBottom: '1px solid #f1f3f5' }}><span>{p.name}</span><span className="meta">{p.category}</span></div>)}</div><div style={{ border: '1px solid #eef2f6', borderRadius: 10, padding: 12 }}><b>科目/测算规则</b><p className="meta">项目明细表填数，目标成本测算页只引用汇总。</p>{tpl.costRules.map((r) => <div key={r.id} style={{ padding: '6px 0', borderBottom: '1px solid #f1f3f5' }}><b>{r.subjectName}</b><div className="meta">{r.sourceTable || '-'} · {r.measureBasis || '-'}</div></div>)}</div><div style={{ border: '1px solid #eef2f6', borderRadius: 10, padding: 12 }}><b>税率模板</b><p className="meta">后续项目可复制默认税率后单独调整。</p>{tpl.taxRules.map((r) => <div key={r.id} style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0', borderBottom: '1px solid #f1f3f5' }}><span>{r.name}</span><b>{Number(r.rate) * 100}%</b></div>)}</div></div></section>)}</div>}</div></main>;
}
